name: bmicalculator
description: Body Mass Index calculator

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  url_launcher: ^6.0.10
  font_awesome_flutter: ^9.2.0
  introduction_screen: ^2.1.0
  dots_indicator: ^2.0.0
  flutter_native_splash: ^1.2.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/bmi.jpg

    # Drawer header images
    - assets/left.jpg
    - assets/right.jpg

    # BMI Status images
    - assets/underweight.jpg
    - assets/healthy.jpg
    - assets/overweight.jpg
    - assets/obesity.jpg

    # Manual images
    - assets/manual/right.png
    - assets/manual/left.png
    - assets/manual/index.png
    - assets/manual/done.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/bmi.jpg"